app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      pool-size: 30
  cors:
    allowed-origin: http://localhost:4200